//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.12 at 08:52:40 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmldefs.mydefinitions/dictionary")
package gov.noaa.cls.inventory.xsd.gen2;
